<?php
defined('BASEPATH') || exit('No direct script access allowed');

class AreaInteresse
{

    private static $valor_array;

    function __construct()
    {
        self::$valor_array = array(
            1 => 'ADMINISTRAÇÃO COMERCIAL/VENDAS',
            2 => 'ADMINISTRAÇÃO DE EMPRESAS',
            3 => 'ADMINISTRAÇÃO PÚBLICA',
            4 => 'ADVOCACIA/JURÁDICA',
            5 => 'AGRONOMIA',
            6 => 'ARQUITETURA/URBANISMO',
            7 => 'ARQUIVOLOGIA',
            8 => 'ARTES CÊNICAS',
            9 => 'ARTES GRÁFICAS',
            10 => 'ARTES PLÁSTICAS',
            11 => 'ATENDIMENTO AO CLIENTE - BARES E RESTAURANTES',
            12 => 'ATENDIMENTO AO CLIENTE - TELEFONISTAS/RECEPCIONISTAS',
            13 => 'ATENDIMENTO AO CLIENTE - TELEMARKETING/CALL CENTER',
            14 => 'ATENDIMENTO AO CLIENTE',
            15 => 'AUDITORIA',
            16 => 'BANCOS',
            17 => 'BIBLIOTECONOMIA',
            18 => 'BIOLOGIA/CIÊNCIAS BIOLÓGICAS',
            19 => 'BIOMEDICINA',
            20 => 'CIÊNCIAS SOCIAIS',
            21 => 'CINEMA',
            22 => 'COMÉRCIO',
            23 => 'COMÉRCIO EXTERIOR',
            24 => 'COMPRAS',
            25 => 'COMUNICAÇÃO',
            26 => 'CONSTRUÇÃO CIVIL',
            27 => 'CONTABILIDADE',
            28 => 'CONTROLADORIA',
            29 => 'CULINÁRIA/GASTRONOMIA',
            30 => 'DESENHO INDUSTRIAL',
            31 => 'DESIGN DE INTERIORES',
            32 => 'DESIGN GRÁFICO',
            33 => 'ECOLOGIA/MEIO AMBIENTE',
            34 => 'ECONOMIA',
            35 => 'ENFERMAGEM',
            36 => 'ENGENHARIA DE ALIMENTOS',
            37 => 'ENGENHARIA CIVIL',
            38 => 'ENGENHARIA ELETRÔNICA',
            39 => 'ENGENHARIA ELÉTRICA',
            40 => 'ENGENHARIA MECÂNICA',
            41 => 'ENGENHARIA METALÚRGICA E DE MATERIAIS',
            42 => 'ENGENHARIA DE MINAS',
            43 => 'ENGENHARIA DE PRODUÇÃO',
            44 => 'ENGENHARIA QUÍMICA',
            45 => 'ENGENHARIA - OUTRAS',
            46 => 'ENSINO SUPERIOR E PESQUISA',
            47 => 'ENSINO - OUTROS',
            48 => 'ENTRETERIMENTO',
            49 => 'ESPORTES',
            50 => 'ESTÉTICA',
            51 => 'FARMÁCIA',
            52 => 'FILOSOFIA',
            53 => 'FINANÇAS',
            54 => 'FISCAL',
            55 => 'FÍSICA',
            56 => 'FISIOTERAPIA',
            57 => 'FONOAUDIOLOGIA',
            58 => 'GEOGRAFIA',
            59 => 'GEOLOGIA',
            60 => 'GESTÃO EMPRESARIAL',
            61 => 'HISTÓRIA',
            62 => 'HOTELARIA',
            63 => 'INDÚSTRIA',
            64 => 'INFORMÁTICA/T.I.',
            65 => 'INTERNET',
            66 => 'JORNALISMO',
            67 => 'LETRAS',
            68 => 'LOGÍSTICA',
            69 => 'MANUTENÇÃO INDUSTRIAL',
            70 => 'MANUTENÇÃO PREDIAL',
            71 => 'MATEMÁTICA/ESTATÍSTICA',
            72 => 'MEDICINA/HOSPITALAR',
            73 => 'METEOROLOGIA',
            74 => 'MINERAÇÃO',
            75 => 'MODA',
            76 => 'MUSEOLOGIA',
            77 => 'MÚSICA',
            78 => 'NUTRIÇÃO',
            79 => 'OCEANOGRAFIA',
            80 => 'ODONTOLOGIA',
            81 => 'ORGANIZAÇÃO DE EVENTOS/PRODUÇÃO CULTURAL',
            82 => 'ORGANIZAÇÃO E MÉTODOS',
            83 => 'PEDAGOGIA',
            84 => 'PESQUISA DE MERCADO',
            85 => 'PETROLÍFERA',
            86 => 'PRODUÇÃO/FABRICAÇÃO',
            87 => 'PROFESSOR',
            88 => 'PROPAGANDA/MARKETING',
            89 => 'PSICOLOGIA',
            90 => 'QUALIDADE',
            91 => 'QUÍMICA',
            92 => 'RADIALISMO E TELEVISÃO',
            93 => 'RECURSOS HUMANOS',
            94 => 'RELAÇÕES INTERNACIONAIS',
            95 => 'RELAÇÕES PÚBLICAS',
            96 => 'SECRETARIADO',
            97 => 'SEGURANÇA E SAÚDE NO TRABALHO',
            98 => 'SEGURANÇA PATRIMONIAL',
            99 => 'SEGUROS',
            100 => 'SERVIÇO SOCIAL',
            101 => 'SERVIÇOS',
            102 => 'SERVIÇOS ADMINISTRATIVOS',
            103 => 'SERVIÇOS DOMÉSTICOS',
            104 => 'SERVIÇOS ESPECIALIZADOS - AÇOUGUE',
            105 => 'SERVIÇOS ESPECIALIZADOS - PADARIA/CONFEITARIA',
            106 => 'SERVIÇOS ESPECIALIZADOS - PEIXARIA',
            107 => 'SERVIÇOS GERAIS',
            108 => 'SERVIÇOS TÉCNICOS - ELÉTRICOS',
            109 => 'SERVIÇOS TÉCNICOS - ELETRÔNICOS',
            110 => 'SERVIÇOS TÉCNICOS - MECÂNICOS',
            111 => 'SERVIÇOS TÉCNICOS - OUTROS',
            112 => 'SUPRIMENTOS',
            113 => 'TELECOMUNICAÇÕES',
            114 => 'TERAPIA OCUPACIONAL',
            115 => 'TERCEIRO SETOR/RESPONSABILIDADE SOCIAL',
            116 => 'TRADUÇÃO/INTERPRETAÇÃO',
            117 => 'TRANSPORTE AÉREO',
            118 => 'TRANSPORTE MARÍTIMO',
            119 => 'TRANSPORTE TERRESTRE',
            120 => 'TRIBUTÁRIA',
            121 => 'TURISMO',
            122 => 'VENDAS',
            123 => 'VENDAS - VAREJO',
            124 => 'VENDAS - TÉCNICAS',
            125 => 'VETERINÁRIA',
            126 => 'WEB DESIGN',
            127 => 'ZOOLOGIA',
            128 => 'ZOOTECNIA'
        );
    }

    public static function ObterValorArray()
    {
        return self::$valor_array;
    }
}